### ISSUE TITLE
ValueError: could not convert string to float: no_constraint for tree_assembler.py

### ISSUE THREAD

**Issue by ynzhangrong** [jfwalker/PHAIL#1]
Hi Joe,

When I executed the script "tree_assembler.py" by python2, I met the following error. Could you give me some suggestions to fix it. Thank you very much.

Rong

"Traceback (most recent call last):
  File "src/tree_assembler.py", line 110, in <module>
    main()
  File "src/tree_assembler.py", line 56, in main
    summed_likelihoods = summarizer.col_like_test(aa,args.support)
  File "/PHAIL/src/summarizer.py", line 379, in col_like_test
    a[count] += float(j)
ValueError: could not convert string to float: no_constraint"

**Comment by jfwalker** [comment]
Happy to take a look, do you mind posting the command that you ran? Also, would you be able to share the likelihood file that was created by the main program? Thanks!

**Comment by ynzhangrong** [comment]
Joe, thanks for your rapid response. 
I tried your example, the workflow and the command line in your github. The command line: python2 src/tree_assembler.py -l output_folder/Likelihoods_raxml.csv -b output_folder/bipartitions.txt -c output_folder/conflicts.txt -m tree
[output_folder.zip](https://github.com/jfwalker/PHAIL/files/5715057/output_folder.zip)
[src.zip](https://github.com/jfwalker/PHAIL/files/5715065/src.zip)

**Comment by jfwalker** [comment]
Interesting, the issue is the Likelihoods_raxml.csv file actually has the header twice. If you remove one of the headers, so the first line in the file, then it should work. I'm not sure what caused that to be part of the output but I should have time this weekend or early next week to fix that and figure out what's going on. For now if you remove one of the headers and run the same command it should work. Thanks for testing this out and letting me know about this!

**Comment by ynzhangrong** [comment]
Thanks your answer. I noted Likelihoods_raxml.csv file has the header twice but couldn't locate to this problem. 
Cheers.
