### ISSUE TITLE
Error option restart mode

### ISSUE THREAD

**Issue by Ptero64** [jfwalker/PHAIL#2]
Hello,

I would like to test PHAIL on a database of ~ 1000 loci and 66 taxa. Iam running it on an HPC but it take a very long time and go above of the time limit. So I think I can use the restart mode but I god this error message when I try it:

``` 
un Starting August 31, 2021 10:56:18
Reading in All66Taxa.log
Traceback (most recent call last):
  File "src/PHAIL.py", line 225, in <module>
    main()
  File "src/PHAIL.py", line 62, in main
    gene_names,gene_models,output_folder,program,path = Extras.get_checkpoint_info(checkfile)
  File "/data/scratch/btx246/Phylo_Phyllostomidae/PHAIL/src/Extras.py", line 43, in get_checkpoint_info
    return ",".join(all_genes), ",".join(gene_models), folder_name, program, path
UnboundLocalError: local variable 'program' referenced before assignment
```
my commande line are:
```
python src/PHAIL.py -s Concatenation_1109loci_66taxa.fas -q partition_1109loci_66taxa.txt -t 1109_Trees.tre -i /data/home/btx246/IQTree/bin/iqtree2 -l All66Taxa.log -z -v 50

python src/PHAIL.py -c All66Taxa.log -z
```
Thanks for the help and advices.

regards

**Comment by jfwalker** [comment]
Hey a dataset that size will probably take a very long time depending upon levels of conflict, we're looking into a way to sort of narrow down what is examined but for now it looks like it's an issue reading the path from the logfile, would you mind sharing the logfile?

**Comment by Ptero64** [comment]
Hi, Thank you for your answer. Yes I can share the logfiles. 
Indeed it will took forever I think with y data (have to do 2799 constraint search for each gene...). I was wondering if parallel or array can be used instead to speed up the process? 

[All66Taxa.log.txt](https://github.com/jfwalker/PHAIL/files/7083705/All66Taxa.log.txt)
[PHAIL_v50.o1659050.txt](https://github.com/jfwalker/PHAIL/files/7083707/PHAIL_v50.o1659050.txt)
Thanks
regards
Nicolas

**Comment by jfwalker** [comment]
Hey Nicolas,

So it looks like the checkpoint file never recorded the genes that were processed, which my only guess could be that it has something to do with the HPC going above the time limit. Most datasets have not been this size and the only issues I when testing this on an HPC was a power outage and that seemed to restart alright. I guess one of the questions would be if anything was written to the Likelihoods_iqtree.csv? In theory the 9 genes that finished should be written in there.

Overall, there are a number of things that are causing this to be a bit slow, we kind of talk about the computational issues in the paper (The name PHAIL is sort of a reference to there needing to be more work on getting this feasible for all datasets). We're working on addressing them, as you mention parallel would be a good implementation and also ways of limiting the bipartitions it tests (also to allow it to handle missing data as well). I just started a new position last week which has put a bit of slowdown on that, but hopefully we should have some updates on this shortly. Overall though with over 1000 genes and 2799 unique bipartitions in the dataset your dataset may be one that's a bit too big for this procedure. One way to greatly limit the bipartitions checked would be to only use those with perfect support or something higher than 50 since it would be unlikely to have a relationship in the dataset that doesn't have perfect support for at least one of the genes.

**Comment by Ptero64** [comment]
Yes there is output for 9 genes in the csv. Job on the HPC cant go more than 10 days.
[Likelihoods_iqtree.csv](https://github.com/jfwalker/PHAIL/files/7084233/Likelihoods_iqtree.csv)
Ok thanks for advices, I will look using a threshold of perfect bootstrap how many unique bipartitions there will be. 
Your paper in sysbiol is very interesting and I willbe happy to test your method with the future update on it. (Interrested also by missing data; in fact the dataset is transcriptome so I run analyses for ~15000 loci)

**Comment by Ptero64** [comment]
For info, with full node support it is reduced to 542 unique bipartitions. Will see if I can complete a run to explore the results (maybe also try with less genes).
Thanks
Best regards
Nicolas

**Comment by jfwalker** [comment]
Thanks so much for the kind words about the paper! And will definitely take you up on testing the future versions. Another option is that in the runs raxml-ng appears to be a bit quicker for constraints, so using raxml-ng instead may help, but overall a dataset your size may just be too large to run the full approach. 
Another option could be to use this more as a support method/looking at gene influence approach. If the input you use is the results of the different reconstruction methods (eg. Astral, Supermatrix, SVDquartets etc), then you should be able to see genes driving each result. It's not as much a reconstruction method then but it's a way to explore the support for the different species tree approaches.

**Comment by Ptero64** [comment]
Yes the idea was to use it in completement to others methods (concat; astral; SVDquartet; PhyParts; Quartet Sampling; concordance factor IQtree; GGI, filtering datasets etc..); as we have two main divergent topologies for a backbone node (systematic error? / increase of phylogenetic signal with genomic scale /ILS/ node trap in anomaly zone?). 
Will test also using raxmlng instead of iqtree.

**Comment by jfwalker** [comment]
Sounds like a really interesting project, curious to see what you find. I think if you used the species trees from other methods as input trees, this will analyze the bipartitions in those and tell you which topologies it supports. It won't uncover any new possible topologies but will at least let you know out of concat, astral, svd etc. which of the relationships in those trees the edge based approach supports.

**Comment by Ptero64** [comment]
Hi Joseph,

Sorry to recontact you, I have some new questions about PHAIL. I have finaly run the program as you recommended using as input tree only 6 topologies inferred by the different methods. I am using 1106 loci with all 66 taxa (no missing data). I have splited my input in 3 parts to be able to run it in time o a cluster (time limit 10 days). 
I was thinking to combine the likelihood.csv of the three run before to run tree_assembler?

I tested on one output tree_assembler.py And I dont really understand all the different output. For example, running option -m tree I have 8 differents trees?
[Option_Tree.tre.txt](https://github.com/jfwalker/PHAIL/files/7284382/Option_Tree.tre.txt)
Is the last one my consensus? What's are the others?

 To indetify genes supporting one of the topology which option is the best to run, -m conflict?
 
 Last I dont understand this warning in the log file (line 12, can't make constraint for: ...."). Is list all of the 66 taxa (and an extra | ?).
[SpeciesTree_part2.log](https://github.com/jfwalker/PHAIL/files/7284428/SpeciesTree_part2.log)

Thnak you in advance for the help,
Best regards
Nicolas

**Comment by jfwalker** [comment]
Hi Nicolas,

For the last part, that is simply the program mentioning that one of the input trees appears to be rooted on a single taxa and so a constraint is not made for the rooted edge because a constraint cannot be made for a single taxa.

For the trees the first one that appears is the one that contains the most likely edge. So it will first put in the most likely edge and then start adding the other edges into the tree in order of their likelihood. If an edge cannot be added in because it conflicts with something already in the tree then it is saved. All the edges that could not be used as starting edges are then used by the program as the starting edge, instead of the most likely edge. Then the consensus tree (the final one in the file) is composed of all the edges that are concordant from the assembled trees. The thing I'm not sure about is the addition of this (-2120883.921) at the beginning of your trees. If you have the input, you may have to email it I added my email below, I can take a look at why that is. 

For adding the genes onto the tree you'll want to use the "conflict" option. Then with that option you need to add a loglikelihood support so that it will report the edges that conflict and in the case of say 2 also have 2 loglikelihood support greater for the alternative edge. If you set support to 0 then it will just give all genes in conflict.
An example would be:
```python PHAIL/src/tree_assembler.py -b output_folder/bipartitions.txt -c output_folder/conflicts.txt -m conflict -l output_folder/Likelihoods_raxml.csv -s 2```

Hope this helps and it somethings not clear or you'd like me to take a look at the 3 input files feel free to email at jfwalker[insert at sign]umich.edu

Best,
Joe
